datasource:
  driver-class-name: oracle.jdbc.OracleDriver
  url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
  username: zy
  password: zy
jpa:
  hibernate:
    ddl-auto: update
    show-sql: true

    #公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
    mybatis:
      typeAliasesPackage: com.xdd.entity
      mapperLocations: classpath:mapper/*.xml